### ISSUE TITLE
Uh... You will be more useful elsewhere...

### ISSUE THREAD

**Issue by MilkAndCookiz** [ExtraCorePE/ExtraCorePE#55]
We needs help to develop [Cookie-MP](https://github.com/CookieSoftware/Cookie-MP) ... I see your software is not moving forward. Do you want the whole team comes on [Cookie-MP](https://github.com/CookieSoftware/Cookie-MP) ? You will be more useful on Cookie-MP. This is not an advertisement... Answer me before closing this issue.

**Comment by xISRAPILx** [comment]
Enough ... The meaning of going to your core, if there ? @CookieCode

**Comment by Nought57** [comment]
@CookieCode Many people misunderstand, but I do not want to become famous. The purpose of making is different. Development is stopping because I'm busy. Many src are ruthless, it will be discontinued at the end in order to rush development, in the end. So, I will relax and make src here. Also, the intention of developers who disappeared remains in ExtraCorePE. This is the answer.
